
services:
  mufarm-db:
    image: postgres:16
    container_name: mufarm-postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: mufarmdb
    ports:
      - "5432:5432"
    volumes:
      - mufarm_data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pgadmin_gui
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@portfolio.com
      PGADMIN_DEFAULT_PASSWORD: adminpassword
    ports:
      - "5050:80" # Maps port 80 inside the container to http://localhost:5050
    depends_on:
      - mufarm-db

volumes:
  mufarm_data: